backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "static/images" # Media files will be stored in the repo under images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
 - name: product
   label: Products
   folder: "content/products"
   create: true
   fields:
   - {label: "id", name: "id", widget: "string"}
   - {label: "Title", name: "title", widget: "string"}
   - {label: "price", name: "price", widget: "number", valueType: "float", default: 0}
   - {label: "description", name: "description", widget: "text"}
   - {label: "Product image", name: "product_image", widget: image}
   - {label: "product_url", name: "product_url", widget: "string"}
   
   
